import '../globals.scss'

import { Roboto } from 'next/font/google'
import type { Metadata } from 'next';
import { dir } from 'i18next'

import Navbar from '@/components/Navbar';
import { useTranslation } from '@/i18n';
import { languages } from '@/i18n/settings';

const inter = Roboto({
  subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'],
  weight: ['100', '300', '400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children, params: { lang } }: { children: React.ReactNode, params: any }) {
  const { t } = await useTranslation(lang, 'navbar')

  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>
        <Navbar lang={lang} t={t} />
        {children}
      </body>
    </html>
  )
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}