import './globals.scss'
import { Roboto } from 'next/font/google'
import type { Metadata } from 'next';

const inter = Roboto({
  subsets: ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'],
  weight: ['100', '300', '400', '500', '700', '900']
})

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
